# Generated by Django 6.0.3 on 2026-03-11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EvaluationSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("participant_id", models.CharField(max_length=128)),
                ("condition", models.CharField(max_length=64)),
                ("session_order", models.CharField(blank=True, max_length=64)),
                ("notes", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={"ordering": ["-started_at"]},
        ),
        migrations.CreateModel(
            name="BlockRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase", models.CharField(max_length=64)),
                ("consistency_score", models.IntegerField()),
                ("adaptation_score", models.IntegerField()),
                ("stability_score", models.IntegerField()),
                ("believability_score", models.IntegerField()),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="block_ratings", to="ui.evaluationsession"),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
        migrations.CreateModel(
            name="FinalPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("preferred_system", models.CharField(max_length=64)),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="final_preference", to="ui.evaluationsession"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InteractionTurn",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("phase", models.CharField(max_length=64)),
                ("turn_number", models.PositiveIntegerField()),
                ("user_input", models.TextField()),
                ("agent_output", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="turns", to="ui.evaluationsession"),
                ),
            ],
            options={"ordering": ["created_at"]},
        ),
    ]
